In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel(r"C:\Users\abrar\Downloads\c4fe3a02-800a-48ae-b5bc-15bbc219f46a.xlsx")
df

       Month  Sales  Expenses  Profit  Customers
0    January  45000     30000   15000        120
1   February  52000     32000   20000        135
2      March  48000     31000   17000        128
3      April  60000     35000   25000        150
4        May  65000     38000   27000        165
5       June  58000     36000   22000        145
6       July  72000     40000   32000        180
7     August  68000     39000   29000        172
8  September  75000     42000   33000        190
9    October  80000     45000   35000        205

In [3]:
df.head(10)

       Month  Sales  Expenses  Profit  Customers
0    January  45000     30000   15000        120
1   February  52000     32000   20000        135
2      March  48000     31000   17000        128
3      April  60000     35000   25000        150
4        May  65000     38000   27000        165
5       June  58000     36000   22000        145
6       July  72000     40000   32000        180
7     August  68000     39000   29000        172
8  September  75000     42000   33000        190
9    October  80000     45000   35000        205

In [4]:
df.tail(10)

       Month  Sales  Expenses  Profit  Customers
0    January  45000     30000   15000        120
1   February  52000     32000   20000        135
2      March  48000     31000   17000        128
3      April  60000     35000   25000        150
4        May  65000     38000   27000        165
5       June  58000     36000   22000        145
6       July  72000     40000   32000        180
7     August  68000     39000   29000        172
8  September  75000     42000   33000        190
9    October  80000     45000   35000        205

In [5]:
df.columns

Index(['Month', 'Sales', 'Expenses', 'Profit', 'Customers'], dtype='str')

In [6]:
df.dtypes

Month          str
Sales        int64
Expenses     int64
Profit       int64
Customers    int64
dtype: object

In [7]:
df.memory_usage()

Index        132
Month         80
Sales         80
Expenses      80
Profit        80
Customers     80
dtype: int64

In [8]:
df.describe(include='all')

          Month         Sales      Expenses        Profit   Customers
count        10     10.000000     10.000000     10.000000   10.000000
unique       10           NaN           NaN           NaN         NaN
top     January           NaN           NaN           NaN         NaN
freq          1           NaN           NaN           NaN         NaN
mean        NaN  62300.000000  36800.000000  25500.000000  159.000000
std         NaN  11747.813035   4917.090377   6900.080515   28.003968
min         NaN  45000.000000  30000.000000  15000.000000  120.000000
25%         NaN  53500.000000  32750.000000  20500.000000  137.500000
50%         NaN  62500.000000  37000.000000  26000.000000  157.500000
75%         NaN  71000.000000  39750.000000  31250.000000  178.000000
max         NaN  80000.000000  45000.000000  35000.000000  205.000000

In [9]:
df.nunique()

Month        10
Sales        10
Expenses     10
Profit       10
Customers    10
dtype: int64

In [10]:
df.isnull().sum()

Month        0
Sales        0
Expenses     0
Profit       0
Customers    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['Expenses'].duplicated().sum()

np.int64(0)