In [55]:
import pandas as pd

In [56]:
df=pd.read_excel(r"C:\Users\abrar\Downloads\c1f5fb48-ba6c-4464-919d-4aba384c7c80.xlsx",names=["Emp_ID",
        "Name",
        "Age",
        "Gender",
        "Salary",
        "Department",
        "Joining_Date"])
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [57]:
df.head(10)

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
1006,Deepa,27,F,HR,"48,000",NaN,15/02/2022,NaN,NaN
1007,Priya,Thirty,NaN,NaN,NaN,Bangalore,2024/03/01,NaN,invalidemail
1008,Aisha,27,NaN,Marketing,"48,000",NaN,2023-01-15,Excellent,invalidemail
1009,Mohammed,NaN,M,NaN,55000,NaN,2023-01-15,NaN,user@example.com
1010,Mohammed,25,F,HR,"48,000",Bangalore,NaN,NaN,invalidemail

In [58]:

df.shape

(100, 7)

In [59]:
df.isnull().sum()

Emp_ID          25
Name            15
Age             23
Gender          30
Salary          17
Department      19
Joining_Date    25
dtype: int64

In [60]:
df.dtypes

Emp_ID             str
Name               str
Age             object
Gender             str
Salary             str
Department         str
Joining_Date       str
dtype: object

In [61]:
df['Age']=pd.to_numeric(df['Age'],errors='coerce')

In [62]:
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,NaN,55000.0,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
1003,Anu,Thirty,F,Sales,NaN,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,good,user@example.com
1005,Aisha,25,NaN,IT,NaN,NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000.0,kochi,2024/03/01,good,NaN
1097,Mohammed,29,Male,HR,35000.0,NaN,15/02/2022,Excellent,invalidemail
1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000.0,Kochi,15/02/2022,NaN,invalidemail
1100,Sara,31,Female,IT,55000.0,NaN,2023-01-15,Poor,invalidemail

In [63]:
df.dtypes

Emp_ID              str
Name                str
Age             float64
Gender              str
Salary              str
Department          str
Joining_Date        str
dtype: object

In [64]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,NaN,55000.00000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269.84127,Calicut,2023-01-15,NaN,invalidemail
1003,Anu,Thirty,F,Sales,45269.84127,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000.00000,Calicut,15/02/2022,good,user@example.com
1005,Aisha,25,NaN,IT,45269.84127,NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000.00000,kochi,2024/03/01,good,NaN
1097,Mohammed,29,Male,HR,35000.00000,NaN,15/02/2022,Excellent,invalidemail
1098,Anu,22,Male,HR,45269.84127,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000.00000,Kochi,15/02/2022,NaN,invalidemail
1100,Sara,31,Female,IT,55000.00000,NaN,2023-01-15,Poor,invalidemail

In [65]:
df['Salary']=pd.to_numeric(df['Salary'],errors='coerce')
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,NaN,55000.00000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269.84127,Calicut,NaN,NaN,invalidemail
1003,Anu,Thirty,F,Sales,45269.84127,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000.00000,Calicut,NaN,good,user@example.com
1005,Aisha,25,NaN,IT,45269.84127,NaN,NaN,Good,NaN
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000.00000,kochi,NaN,good,NaN
1097,Mohammed,29,Male,HR,35000.00000,NaN,NaN,Excellent,invalidemail
1098,Anu,22,Male,HR,45269.84127,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000.00000,Kochi,NaN,NaN,invalidemail
1100,Sara,31,Female,IT,55000.00000,NaN,NaN,Poor,invalidemail

In [66]:
df["Name"]=df["Name"].fillna("Unknown")
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,Unknown,55000.00000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269.84127,Calicut,NaN,NaN,invalidemail
1003,Anu,Thirty,F,Sales,45269.84127,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000.00000,Calicut,NaN,good,user@example.com
1005,Aisha,25,NaN,IT,45269.84127,NaN,NaN,Good,NaN
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000.00000,kochi,NaN,good,NaN
1097,Mohammed,29,Male,HR,35000.00000,NaN,NaN,Excellent,invalidemail
1098,Anu,22,Male,HR,45269.84127,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000.00000,Kochi,NaN,NaN,invalidemail
1100,Sara,31,Female,IT,55000.00000,NaN,NaN,Poor,invalidemail

In [67]:
df["Department"]=df["Department"].fillna(df["Department"].mode()[0])
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,Unknown,55000.00000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269.84127,Calicut,NaN,good,invalidemail
1003,Anu,Thirty,F,Sales,45269.84127,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000.00000,Calicut,NaN,good,user@example.com
1005,Aisha,25,NaN,IT,45269.84127,NaN,NaN,Good,NaN
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000.00000,kochi,NaN,good,NaN
1097,Mohammed,29,Male,HR,35000.00000,NaN,NaN,Excellent,invalidemail
1098,Anu,22,Male,HR,45269.84127,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000.00000,Kochi,NaN,good,invalidemail
1100,Sara,31,Female,IT,55000.00000,NaN,NaN,Poor,invalidemail

In [68]:
df["Joining_Date"]=df["Joining_Date"].fillna("2023-01-01")
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,Unknown,55000.00000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269.84127,Calicut,NaN,good,invalidemail
1003,Anu,Thirty,F,Sales,45269.84127,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000.00000,Calicut,NaN,good,user@example.com
1005,Aisha,25,NaN,IT,45269.84127,NaN,NaN,Good,2023-01-01
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000.00000,kochi,NaN,good,2023-01-01
1097,Mohammed,29,Male,HR,35000.00000,NaN,NaN,Excellent,invalidemail
1098,Anu,22,Male,HR,45269.84127,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000.00000,Kochi,NaN,good,invalidemail
1100,Sara,31,Female,IT,55000.00000,NaN,NaN,Poor,invalidemail

In [69]:
df["Emp_ID"]=df["Emp_ID"].astype(int)
df

ValueError: invalid literal for int() with base 10: 'Female'

In [70]:

df["Age"] = df["Age"].astype(int)
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269,Calicut,NaN,good,invalidemail
1003,Anu,Thirty,F,Sales,45269,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000,Calicut,NaN,good,user@example.com
1005,Aisha,25,NaN,IT,45269,NaN,NaN,Good,2023-01-01
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000,kochi,NaN,good,2023-01-01
1097,Mohammed,29,Male,HR,35000,NaN,NaN,Excellent,invalidemail
1098,Anu,22,Male,HR,45269,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000,Kochi,NaN,good,invalidemail
1100,Sara,31,Female,IT,55000,NaN,NaN,Poor,invalidemail

In [71]:
df["Salary"] = df["Salary"].astype(float)
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269,Calicut,NaN,good,invalidemail
1003,Anu,Thirty,F,Sales,45269,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000,Calicut,NaN,good,user@example.com
1005,Aisha,25,NaN,IT,45269,NaN,NaN,Good,2023-01-01
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000,kochi,NaN,good,2023-01-01
1097,Mohammed,29,Male,HR,35000,NaN,NaN,Excellent,invalidemail
1098,Anu,22,Male,HR,45269,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000,Kochi,NaN,good,invalidemail
1100,Sara,31,Female,IT,55000,NaN,NaN,Poor,invalidemail

In [72]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
df

C:\Users\abrar\AppData\Local\Temp\ipykernel_18488\2577901101.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

DateParseError: Unknown datetime string format, unable to parse:  test@mail.com

In [73]:
df["Gender"] = df["Gender"].astype("category")
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269,Calicut,NaN,good,invalidemail
1003,Anu,Thirty,F,Sales,45269,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000,Calicut,NaN,good,user@example.com
1005,Aisha,25,NaN,IT,45269,NaN,NaN,Good,2023-01-01
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000,kochi,NaN,good,2023-01-01
1097,Mohammed,29,Male,HR,35000,NaN,NaN,Excellent,invalidemail
1098,Anu,22,Male,HR,45269,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000,Kochi,NaN,good,invalidemail
1100,Sara,31,Female,IT,55000,NaN,NaN,Poor,invalidemail

In [74]:
df["Department"] = df["Department"].astype("category")
df

,,,Emp_ID,Name,Age,Gender,Salary,Department,Joining_Date
1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1002,Kiran,31,M,Marketing,45269,Calicut,NaN,good,invalidemail
1003,Anu,Thirty,F,Sales,45269,NaN,NaN,Good,test@mail.com
1004,John,27,F,Marketing,35000,Calicut,NaN,good,user@example.com
1005,Aisha,25,NaN,IT,45269,NaN,NaN,Good,2023-01-01
...,...,...,...,...,...,...,...,...,...
1096,Anu,27,Male,Sales,42000,kochi,NaN,good,2023-01-01
1097,Mohammed,29,Male,HR,35000,NaN,NaN,Excellent,invalidemail
1098,Anu,22,Male,HR,45269,NaN,NaN,good,test@mail.com
1099,Arun,22,Female,IT,42000,Kochi,NaN,good,invalidemail
1100,Sara,31,Female,IT,55000,NaN,NaN,Poor,invalidemail

In [75]:
print(df.dtypes)

Emp_ID               str
Name                 str
Age                int64
Gender          category
Salary           float64
Department      category
Joining_Date         str
dtype: object

In [77]:
df.shape

(100, 7)

In [78]:
df.isnull().sum(axis=1)

1001  Rahul     22        1
1002  Kiran     31        1
1003  Anu       Thirty    2
1004  John      27        1
1005  Aisha     25        3
                         ..
1096  Anu       27        1
1097  Mohammed  29        2
1098  Anu       22        2
1099  Arun      22        1
1100  Sara      31        2
Length: 100, dtype: int64

In [79]:
df.dropna()

Empty DataFrame
Columns: [Emp_ID, Name, Age, Gender, Salary, Department, Joining_Date]
Index: []